######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 28 15:36:09 2016
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += libinstaller gui
