#ifndef LIBINSTALLER_GLOBAL_H
#define LIBINSTALLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBINSTALLER_LIBRARY)
#  define LIBINSTALLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBINSTALLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBINSTALLER_GLOBAL_H
